FROM almalinux/9-base
LABEL name="kiran" \
trainer="shivakumar"
## label is used for giving tag so that we can filter also .. docker images -f "label=trainer=shivakumar" ..
EXPOSE 80/tcp
## expose port to the world unknow people can see the port
CMD ["sleep","11"]
