FROM almalinux
ADD https://en.wikipedia.org/wiki/Computer_file /tmp/notes.txt
## add also same like copy but it takes data from google but not like local copy
CMD ["sleep","15"]
## almalinux is os it can't open for always so we are giving task like sleep to open for 15 sec

