FROM almalinux
RUN dnf install nginx -y
CMD ["systemctl","start","nginx"]
## using run command we can install nginx in almalinux but to start we require cmd command to start nginx inside the container